/*
 Resources.swift

 This source file is part of the Workspace open source project.
 Diese Quelldatei ist Teil des quelloffenen Arbeitsbereich‐Projekt.
 https://github.com/SDGGiesbrecht/Workspace#workspace

 Copyright ©2018–2022 Jeremy David Giesbrecht and the Workspace project contributors.
 Urheberrecht ©2018–2022 Jeremy David Giesbrecht und die Mitwirkenden des Arbeitsbereich‐Projekts.

 Soli Deo gloria.

 Licensed under the Apache Licence, Version 2.0.
 See http://www.apache.org/licenses/LICENSE-2.0 for licence information.
 */

import Foundation

internal enum Resources {}
internal typealias Ressourcen = Resources

extension Resources {
  internal static let contributingTemplate = String(
    data: Data(
      base64Encoded:
        "IyBDb250cmlidXRpbmcgdG8gI3BhY2thZ2VOYW1lCgpFdmVyeW9uZSBpcyB3ZWxjb21lIHRvIGNvbnRyaWJ1dGUgdG8gI3BhY2thZ2VOYW1lIQoKIyMgU3RlcCAxOiBSZXBvcnQKCkZyb20gdGhlIHNtYWxsZXN0IHR5cG8gdG8gdGhlIHNldmVyZXN0IGNyYXNoLCB3aGV0aGVyIHlvdSBhcmUgcmVwb3J0aW5nIGEgYnVnIG9yIHJlcXVlc3RpbmcgYSBuZXcgZmVhdHVyZSwgd2hldGhlciB5b3UgYWxyZWFkeSBoYXZlIGEgc29sdXRpb24gaW4gbWluZCBvciBub3QsIHBsZWFzZSAqKmFsd2F5cyBzdGFydCBieSByZXBvcnRpbmcgaXQqKi4KClBsZWFzZSBzZWFyY2ggdGhlIFtleGlzdGluZyBpc3N1ZXNdKC4uLy4uL2lzc3VlcykgdG8gc2VlIGlmIHNvbWV0aGluZyByZWxhdGVkIGhhcyBhbHJlYWR5IGJlZW4gcmVwb3J0ZWQuCgotIElmIHRoZXJlIGlzIGFscmVhZHkgYSByZWxhdGVkIGlzc3VlLCBwbGVhc2Ugam9pbiB0aGF0IGNvbnZlcnNhdGlvbiBhbmQgc2hhcmUgYW55IGFkZGl0aW9uYWwgaW5mb3JtYXRpb24geW91IGhhdmUuCi0gT3RoZXJ3aXNlLCBvcGVuIGEgW25ldyBpc3N1ZV0oLi4vLi4vaXNzdWVzL25ldykuCgpFdmVuIGlmIHlvdSB0aGluayB5b3UgaGF2ZSB0aGUgc29sdXRpb24sIHBsZWFzZSAqKmRvIG5vdCBzdGFydCB3b3JraW5nIG9uIGl0KiogdW50aWwgeW91IGhlYXIgZnJvbSBvbmUgb2YgdGhlIHByb2plY3QgYWRtaW5pc3RyYXRvcnMuIFRoaXMgbWF5IHNhdmUgeW91IHNvbWUgd29yayBpbiB0aGUgZXZlbnQgdGhhdCBzb21lb25lIGVsc2UgaXMgYWxyZWFkeSB3b3JraW5nIG9uIGl0LCBvciBpZiB5b3VyIGlkZWEgZW5kcyB1cCBkZWVtZWQgYmV5b25kIHRoZSBzY29wZSBvZiB0aGUgcHJvamVjdCBnb2Fscy4KCiMjIFN0ZXAgMjogQnJhbmNoCgpJZiB5b3UgaGF2ZSBbcmVwb3J0ZWRdKCNzdGVwLTEtcmVwb3J0KSB5b3VyIGlkZWEgYW5kIGFuIGFkbWluaXN0cmF0b3IgaGFzIGdpdmVuIHlvdSB0aGUgZ3JlZW4gbGlnaHQsIGZvbGxvdyB0aGVzZSBzdGVwcyB0byBnZXQgYSBsb2NhbCBjb3B5IHlvdSBjYW4gd29yayBvbi4KCjEuICoqRm9yayB0aGUgcmVwb3NpdG9yeSoqIGJ5IGNsaWNraW5nIOKAnEZvcmvigJ0gaW4gdGhlIHRvcOKAkHJpZ2h0IG9mIHRoZSByZXBvc2l0b3J5IHBhZ2UuIChTa2lwIHRoaXMgc3RlcCBpZiB5b3UgaGF2ZSBiZWVuIGdpdmVuIHdyaXRlIGFjY2Vzcy4pCjIuICoqQ3JlYXRlIGEgbG9jYWwgY2xvbmUqKi4jY2xvbmVTY3JpcHQKMy4gKipDcmVhdGUgYSBkZXZlbG9wbWVudCBicmFuY2gqKi4gYGdpdCBjaGVja291dCAtYiBzb21l4oCQbmV34oCQYnJhbmNo4oCQbmFtZWAKNC4gKipTZXQgdXAgdGhlIHdvcmtzcGFjZSoqIGJ5IGRvdWJsZeKAkGNsaWNraW5nIGBSZWZyZXNoYCBpbiB0aGUgcm9vdCBmb2xkZXIuIChJZiB5b3VyIHN5c3RlbSBpcyBzZXQgdG8gKmVkaXQqIHNjcmlwdHMgaW5zdGVhZCBvZiAqZXhlY3V0ZSogdGhlbSwgeW91IG1heSBoYXZlIHRvIGV4ZWN1dGUgdGhlIGZpbGUgZnJvbSBhIHRlcm1pbmFsIGluc3RlYWQuKQoKTm93IHlvdSBhcmUgYWxsIHNldCB0byB0cnkgb3V0IHlvdXIgaWRlYS4KCiMjIFN0ZXAgMzogU3VibWl0CgpPbmNlIHlvdSBoYXZlIHlvdXIgaWRlYSB3b3JraW5nIHByb3Blcmx5LCBmb2xsb3cgdGhlc2Ugc3RlcHMgdG8gc3VibWl0IHlvdXIgY2hhbmdlcy4KCjEuICoqVmFsaWRhdGUgeW91ciBjaGFuZ2VzKiogYnkgZG91Ymxl4oCQY2xpY2tpbmcgYFZhbGlkYXRlYCBpbiB0aGUgcm9vdCBmb2xkZXIuCjIuICoqQ29tbWl0IHlvdXIgY2hhbmdlcyoqLiBgZ2l0IGNvbW1pdCAtbSAiU29tZSBkZXNjcmlwdGlvbiBvZiB0aGUgY2hhbmdlcy4iYAozLiAqKlB1c2ggeW91ciBjaGFuZ2VzKiouIGBnaXQgcHVzaGAKNC4gKipTdWJtaXQgYSBwdWxsIHJlcXVlc3QqKiBieSBjbGlja2luZyDigJxOZXcgUHVsbCBSZXF1ZXN04oCdIGluIHRoZSBicmFuY2ggbGlzdCBvbiBHaXRIdWIuCjUuICoqV2FpdCBmb3IgY29udGludW91cyBpbnRlZ3JhdGlvbioqIHRvIGNvbXBsZXRlIGl0cyB2YWxpZGF0aW9uLgo2LiAqKlJlcXVlc3QgYSByZXZpZXcqKiBmcm9tICNhZG1pbmlzdHJhdG9ycyBieSBjbGlja2luZyB0aGUgZ2VhciBpbiB0aGUgdG9wIHJpZ2h0IG9mIHRoZSBwdWxsIHJlcXVlc3QgcGFnZS4K"
    )!,
    encoding: String.Encoding.utf8
  )!
  internal static let mitwirkenVorlage = String(
    data: Data(
      base64Encoded:
        "IyBCZWkgI3BhY2thZ2VOYW1lIG1pdHdpcmtlbgoKSmVkZXIgaXN0IHdpbGxrb21tZW4sIGJlaSAjcGFja2FnZU5hbWUgbWl0enV3aXJrZW4hCgojIyBTY2hyaXR0IDE6IE1lbGRlbgoKVm9tIGtlaW5zdGVuIFRpcHBmZWhsZXIgYmlzIHp1bSBzY2hsaW1tc3RlciBBYnN0dXJ6LCBvYiB6dW0gbWVsZGVuIGVpbmVzIEZlaGxlcnMgb2RlciB6dW0gYW5mb3JkZXJuIGVpbmVzIG5ldWVzIE1lcmttYWxzLCBvYiBTaWUgc2Nob24gdm9uIGVpbmVyIExvzIhzdW5nIHdlacOfIG9kZXIgbmljaHQsIGJpdHRlICoqbWVsZGVuIFNpZSBlcyBpbW1lciB6dWVyc3QgYW4qKi4KCkJpdHRlIHN1Y2hlbiBTaWUgZGllIFtiZXJlaXRzIGJlc3RlaGVuZGUgVGhlbWVuXSguLi8uLi9pc3N1ZXMpLCBmYWxscyBhzIhobmxpY2hlcyBzY2hvbiBnZW1lbGRldCBpc3QuCgotIFdlbm4gZWluZSBhzIhobmxpY2hlIFRoZW1hIHNjaG9uIGJlc3RlaGV0LCBiaXR0ZSBuZWhtZW4gU2llIHRlaWwgaW4gZGVtIEdlc3ByYcyIY2ggdW5kIG1lbGRlbiBTaWUgaXJnZW53ZWxjaGUgTmV1aWdrZWl0ZW4gZG9ydC4KLSBTb25zdCBvzIhmZm5lbiBTaWUgZWluZSBbbmV1ZSBUaGVtYV0oLi4vLi4vaXNzdWVzL25ldykuCgpTZWxic3Qgd2VubiBTaWUgZGllIExvzIhzdW5nIHp1IGhhYmVuIGdsYXViZW4sIGJpdHRlICoqZmFuZ2VuIFNpZSBuaWNodCBhbioqIGJpcyBTaWUgdm9uIGVpbmVtIGRlciBWZXJ3YWx0ZXIgZ2Vob8yIcnQgaGFiZW4uIFNvIGtvzIhubmVuIFNpZSBzaWNoIEFyYmVpdCBzcGFyZW4sIHdlbm4gc29uc3QgamVtYW5kIGRhcyBzZWxiZSBzY2hvbiBhbmdlZmFuZ2VuIGhhdCwgb2RlciB3ZW5uIGVudHNjaGllZGVuIHdpcmQsIGRhc3MgSWhyZSBJZGVlIHNpY2ggZG9jaCBhdcOfZXJoYWxiIGRlciBQcm9qZWt0emllbGUgYmVmaW5kZXQuCgojIyBTY2hyaXR0IDI6IEFiendlaWdlbgoKTmFjaGRlbSBTaWUgSWhyZSBJZGVlIFtnZW1lbGRldF0oI3NjaHJpdHQtMS1tZWxkZW4pIGhhYmVuIHVuZCBlaW4gVmVyd2FsdGVyIElobmVuIGVpbiBncnXMiG5lcyBMaWNodCBnZWdlYmVuIGhhdCwgZm9sZ2VuIFNpZSBkaWVzZSBTY2hyaXR0ZSB1bSBlaW5lIGxva2FsZSBLb3BpZSB6dSBoZXJ6dXN0ZWxsZW4sIGRpZSBTaWUgdmVyYXJiZWl0ZW4ga2/MiG5uZW4uCgoxLiAqKkRhcyBMYWdlciAoKnJlcG9zaXRvcnkqKSBhdWZzcGFsdGVuICgqZm9yayopKiouIEF1ZiDigJ5Gb3Jr4oCcIG9iZW4gcmVjaHRzIGF1ZiBkZXIgTGFnZXJzZWl0ZSBrbGlja2VuLiAoRGllc2VuIFNjaHJpdHQgdcyIYmVyc3ByaW5nZW4sIHdlbm4gc2llIHNjaG9uIFNjaHJlaWJ6dWdyaWZmIGhhYmVuLikKMi4gKipFaW5lbiBsb2thbGVuIE5hY2hiYXUgKCpjbG9uZSopIGVyc3RlbGxlbioqLiNjbG9uZVNjcmlwdAozLiAqKkVpbmVuIEVudHdpY2tsdW5nc3p3ZWlnICgqYnJhbmNoKikgZXJzdGVsbGVuKiouIGBnaXQgY2hlY2tvdXQgLWIgaWdyZW5kd2VsY2hlcuKAkG5ldWVy4oCQendlaWduYW1lYAo0LiAqKkRlbiBBcmJlaXRzYmVyZWljaCBhdWZzdGVsbGVuKiouIEF1ZiBgUmVmcmVzaGAgKCphdWZmcmlzY2hlbiopIGluIGRlciBMYWdlcnd1cnplbCBkb3BwZWxrbGlja2VuLiAoV2VubiBJaHIgU3lzdGVtIHNvIGVpbmdlc3RlbGx0IGlzdCwgZGFzcyBlcyBkYXMgKlZlcmFyYmVpdGVuKiB2b24gU2tyaXB0cyBiZXZvcnp1Z3QsIGFuc3RhdHQgZGFzICpBdXNmdcyIaHJlbiosIGRhbm4gbXXMiHNzZW4gU2llIHZpZWxsZWljaHQgc3RhdHRkZXNzZW4gZGFzIFNrcmlwdCBpbiBlaW5lbSBUZXJtaW5hbCBhdXNmdcyIaHJlbi4pCgpKZXR6dCBzaW5kIFNpZSBiZXJlaXQsIElocmUgSWRlZSB6dSBwcm9iaWVyZW4uCgojIyBTY2hyaXR0IDM6IEVpbnJlaWNoZW4KCk5hY2hkZW0gSWhyZSBJZGVlIGd1dCBmdW5rdGlvbmllcnQsIGZvbGdlbiBTaWUgZGllc2UgU2Nocml0dGUgdW0gSWhyZSBBzIhuZGVydW5nZW4gZWluenVyZWljaGVuLgoKMS4gKipJaHJlIEHMiG5kZXJ1bmdlbiB1zIhiZXJwcnXMiGZlbioqLiBBdWYgYFZhbGlkYXRlYCBpbiBkZXIgTGFnZXJ3dXJ6ZWwgZG9wcGVsa2xpY2tlbi4KMi4gKipJaHJlIEHMiG5kZXJ1bmdlbiB1zIhiZXJnZWJlbiAoKmNvbW1pdCopKiouIGBnaXQgY29tbWl0IC1tICJJcmdlbmR3ZWxjaGUgQmVzY2hyZWlidW5nIGRlciBBzIhuZGVydW5nZW4uImAKMy4gKipJaHJlIEHMiG5kZXJ1bmdlbiBzdG/Dn2VuICgqcHVzaCopKiouIGBnaXQgcHVzaGAKNC4gKipFaW5lIEFiemllaHVuZ3NhbmZvcmRlcnVuZyAoKnB1bGwgcmVxdWVzdCopKiouIOKAnk5ldyBQdWxsIFJlcXVlc3TigJwgaW4gZGVyIFp3ZWlnbGlzdGUgYmVpIEdpdEh1Yi4KNS4gKipBdWYgZGllIHXMiGJlcnBydcyIZnVuZyBkZXIgZm9ydGxhdWZlbmRlbiBFaW5iaW5kdW5nICgqY29udGludW91cyBpbnRlZ3JhdGlvbiopIHdhcnRlbioqLgo2LiAqKkVpbmUgQmV3ZXJ0dW5nICgqcmV2aWV3Kikgdm9uICNhZG1pbmlzdHJhdG9ycyBhbmZvcmRlcm4qKi4gQXVmIGRlbiBaYWhucmFkIG9iZW4gcmVjaHRzIGF1ZiBkZXIgU2VpdGUgZGVyIEFiemllaHVuZ3NhbmZvcmRlcnVuZyBrbGlja2VuLgo="
    )!,
    encoding: String.Encoding.utf8
  )!
  internal static let pullRequestTemplate = String(
    data: Data(
      base64Encoded:
        "PCEtLSBSZW1pbmRlcjoKIEhhdmUgeW91IG9wZW5lZCBhbiBpc3N1ZSBhbmQgZ290dGVuIGEgcmVzcG9uc2UgZnJvbSBhbiBhZG1pbmlzdHJhdG9yPwogQWx3YXlzIGRvIHRoYXQgZmlyc3Q7IHNvbWV0aW1lcyBpdCB3aWxsIHNhdmUgeW91IHNvbWUgd29yay4KIC0tPgoKPCEtLSBGaWxsIGluIHRoZSBpc3N1ZSBudW1iZXIuIC0tPgpUaGlzIHdvcmsgd2FzIGNvbW1pc3Npb25lZCBieSBhbiBhZG1pbmlzdHJhdG9yIGluIGlzc3VlICMwMDAuCgo8IS0tIEtlZXAgb25seSBvbmUgb2YgdGhlIGZvbGxvd2luZyBsaW5lcy4gLS0+CkkgKiphbSBsaWNlbnNpbmcqKiB0aGlzIHVuZGVyIHRoZSBbcHJvamVjdCBsaWNlbmNlXSguLi9ibG9iL21hc3Rlci9MSUNFTlNFLm1kKS4KSSAqKnJlZnVzZSB0byBsaWNlbnNlKiogdGhpcyB1bmRlciB0aGUgW3Byb2plY3QgbGljZW5jZV0oLi4vYmxvYi9tYXN0ZXIvTElDRU5TRS5tZCkuCg=="
    )!,
    encoding: String.Encoding.utf8
  )!

}
