
name: Build cURL for Android
runs:
  using: "composite"
  steps:
    - name: Build cURL for Android
      # Based on https://curl.se/docs/install.html#android
      shell: bash
      run: |
        set -x
        export NDK=${ANDROID_HOME}/ndk-bundle
        export HOST_TAG=linux-x86_64
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/$HOST_TAG
        export AR=$TOOLCHAIN/bin/x86_64-linux-android-ar
        export AS=$TOOLCHAIN/bin/x86_64-linux-android-as
        export CC=$TOOLCHAIN/bin/x86_64-linux-android29-clang
        export CXX=$TOOLCHAIN/bin/x86_64-linux-android29-clang++
        export LD=$TOOLCHAIN/bin/x86_64-linux-android-ld
        export RANLIB=$TOOLCHAIN/bin/x86_64-linux-android-ranlib
        export STRIP=$TOOLCHAIN/bin/x86_64-linux-android-strip
        ./configure --host x86_64-linux-android --with-pic --disable-shared
