excluded:
  - Packages
  - .Test Zone
disabled_rules:
  - colon
  - cyclomatic_complexity
  - empty_parentheses_with_trailing_closure
  - file_length
  - function_body_length
  - function_parameter_count
  - large_tuple
  - line_length
  - type_body_length
  - variable_name
