#if !canImport(ObjectiveC)
import XCTest

extension AllDisabledTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AllDisabledTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AllDisabledTests.__allTests__AllDisabledTests),
    ]
}
#endif
