
name: Build ICU for Android
runs:
  using: "composite"
  steps:
    - name: Build ICU for Android
      # Based on https://htmlpreview.github.io/?https://github.com/unicode-org/icu/blob/master/icu4c/readme.html#HowToCrossCompileICU
      shell: bash
      run: |
        set -x
        mkdir icu4c-build-android
        cd icu4c-build-android
        ../icu/icu4c/source/configure \
          --host=x86_64-unknown-linux-android \
          --with-cross-build=${GITHUB_WORKSPACE}/icu4c-build-linux \
          --prefix=${GITHUB_WORKSPACE}/Android/ICU \
          CC=${GITHUB_WORKSPACE}/Android/C/bin/x86_64-linux-android29-clang \
          CXX=${GITHUB_WORKSPACE}/Android/C/bin/x86_64-linux-android29-clang++ \
          RANLIB=${GITHUB_WORKSPACE}/Android/C/bin/x86_64-linux-android-ranlib \
          AR=${GITHUB_WORKSPACE}/Android/C/bin/x86_64-linux-android-ar \
          --enable-layoutex=no
        make
        make install
        find ${GITHUB_WORKSPACE}/Android/ICU
