#if !canImport(ObjectiveC)
import XCTest

extension CrossPlatformTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CrossPlatformTests = [
        ("testCachePermissions", testCachePermissions),
        ("testGit", testGit),
        ("testReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyLongTestName", testReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyReallyLongTestName),
        ("testRepositoryPresence", testRepositoryPresence),
        ("testTemporaryDirectoryPermissions", testTemporaryDirectoryPermissions),
        ("testTests", testTests),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CrossPlatformTests.__allTests__CrossPlatformTests),
    ]
}
#endif
