#if !canImport(ObjectiveC)
import XCTest

extension APITests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__APITests = [
        ("testAllDisabled", testAllDisabled),
        ("testAllTasks", testAllTasks),
        ("testArray", testArray),
        ("testBadStyle", testBadStyle),
        ("testBrokenExample", testBrokenExample),
        ("testBrokenTests", testBrokenTests),
        ("testCheckedInDocumentation", testCheckedInDocumentation),
        ("testCheckForUpdates", testCheckForUpdates),
        ("testConfiguartionContext", testConfiguartionContext),
        ("testConfiguration", testConfiguration),
        ("testContinuousIntegrationWithoutScripts", testContinuousIntegrationWithoutScripts),
        ("testCustomProofread", testCustomProofread),
        ("testCustomReadMe", testCustomReadMe),
        ("testCustomTasks", testCustomTasks),
        ("testDefaults", testDefaults),
        ("testDeutsch", testDeutsch),
        ("testExecutable", testExecutable),
        ("testFailingCustomTasks", testFailingCustomTasks),
        ("testFailingCustomValidation", testFailingCustomValidation),
        ("testFailingDocumentationCoverage", testFailingDocumentationCoverage),
        ("testFailingTests", testFailingTests),
        ("testHeaders", testHeaders),
        ("testHelp", testHelp),
        ("testInvalidResourceDirectory", testInvalidResourceDirectory),
        ("testInvalidTarget", testInvalidTarget),
        ("testIssueTemplate", testIssueTemplate),
        ("testLazyOption", testLazyOption),
        ("testLicence", testLicence),
        ("testLocalizationIdentifier", testLocalizationIdentifier),
        ("testMissingDocumentation", testMissingDocumentation),
        ("testMissingExample", testMissingExample),
        ("testMissingReadMeLocalization", testMissingReadMeLocalization),
        ("testMultipleProducts", testMultipleProducts),
        ("testNoLibraries", testNoLibraries),
        ("testNoLocalizations", testNoLocalizations),
        ("testNurDeutsch", testNurDeutsch),
        ("testOneLocalization", testOneLocalization),
        ("testOneProductMultipleModules", testOneProductMultipleModules),
        ("testOnlyBritish", testOnlyBritish),
        ("testPartialReadMe", testPartialReadMe),
        ("testProofreadingRule", testProofreadingRule),
        ("testRelatedProject", testRelatedProject),
        ("testSDGLibrary", testSDGLibrary),
        ("testSDGTool", testSDGTool),
        ("testSelfSpecificScripts", testSelfSpecificScripts),
        ("testTestCoverageExemptionToken", testTestCoverageExemptionToken),
        ("testUnicodeRuleScope", testUnicodeRuleScope),
    ]
}

extension InternalTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__InternalTests = [
        ("testGitIgnoreCoverage", testGitIgnoreCoverage),
        ("testPlatform", testPlatform),
        ("testXcodeProjectFormat", testXcodeProjectFormat),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(APITests.__allTests__APITests),
        testCase(InternalTests.__allTests__InternalTests),
    ]
}
#endif
