
name: Build Swift for Linux
runs:
  using: "composite"
  steps:
    - name: Build Swift for Linux
      # Based on https://github.com/apple/swift/blob/master/utils/build-toolchain
      # Also based on https://github.com/apple/swift/blob/master/utils/build-presets.ini
      shell: bash
      run: |
        set -x
        cd swift-source/swift
        ./utils/build-script --release \
          --install-destdir ${GITHUB_WORKSPACE}/Ubuntu/Swift \
          --install-swift \
          --install-lldb --lldb \
          --install-llbuild --llbuild \
          --install-llvm --llvm-install-components 'IndexStore' \
          --indexstore-db \
          --install-swiftpm --swiftpm \
          --install-xctest --xctest \
          --install-libicu --libicu \
          --install-libcxx --libcxx \
          --install-foundation --foundation \
          --install-libdispatch --libdispatch
        ${GITHUB_WORKSPACE}/Ubuntu/Swift/usr/bin/swiftc --version
        ${GITHUB_WORKSPACE}/Ubuntu/Swift/usr/bin/swift --version
        ${GITHUB_WORKSPACE}/Ubuntu/Swift/usr/bin/swift package --version
