
name: Build Swift SDK for Android
runs:
  using: "composite"
  steps:
    - name: Build Swift SDK for Android
      # Based on https://github.com/apple/swift/blob/main/docs/Android.md#2-building-the-swift-stdlib-for-android
      # Also based on https://github.com/buttaface/swift-android-sdk/blob/main/README.md#building-the-android-sdks
      shell: bash
      run: |
        set -x
        cd swift-source/swift
        ./utils/build-script --release --android \
          --install-destdir ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk \
          --android-ndk ${ANDROID_HOME}/ndk-bundle \
          --android-arch x86_64 \
          --android-api-level 29 \
          --android-icu-uc ${GITHUB_WORKSPACE}/Android/ICU/lib/libicuuc.so.67.1 \
          --android-icu-uc-include ${GITHUB_WORKSPACE}/Android/ICU/include/unicode \
          --android-icu-i18n ${GITHUB_WORKSPACE}/Android/ICU/lib/libicui18n.so.67.1 \
          --android-icu-i18n-include ${GITHUB_WORKSPACE}/Android/ICU/include \
          --android-icu-data ${GITHUB_WORKSPACE}/Android/ICU/lib/libicudata.so.67.1 \
          --install-swift
          --install-libdispatch
        find ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk
