
name: Thin Swift SDK for Android
runs:
  using: "composite"
  steps:
    - name: Thin Swift SDK for Android
      shell: bash
      run: |
        set -x
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/bin
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/share/doc
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/share/emacs
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/share/man
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/share/vim
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/share/swift/diagnostics
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/share/swift/features.json
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/share/swift/testsuite
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/lib/swift_static/linux
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/lib/swift/_InternalSwiftScan
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/lib/swift/migrator
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/lib/swift/linux
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/lib/swift/_InternalSwiftSyntaxParser
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/lib/swift/FrameworkABIBaseline
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/lib/libswiftDemangle.so
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/lib/libsourcekitdInProc.so
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/include/SourceKit
        find ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk
