
name: Install Swift dependencies
runs:
  using: "composite"
  steps:
    - name: Install Swift dependencies
      # Based on https://github.com/apple/swift/blob/main/docs/HowToGuides/GettingStarted.md#ubuntu-linux
      shell: bash
      run: |
        set -x
        sudo apt-get update --assume-yes
        sudo apt-get install --assume-yes \
          clang-7 \
          cmake \
          git \
          icu-devtools \
          libcurl4-openssl-dev \
          libedit-dev \
          libicu-dev \
          libncurses5-dev \
          libpython3-dev \
          libsqlite3-dev \
          libxml2-dev \
          ninja-build \
          pkg-config \
          python \
          python-six \
          rsync \
          swig \
          systemtap-sdt-dev \
          tzdata \
          uuid-dev
