
name: Build Foundation for Android
runs:
  using: "composite"
  steps:
    - name: Build Foundation for Android
      # Based on https://github.com/apple/swift/blob/master/docs/AndroidBuild.md#building-swift-sdk-for-android-on-windows
      # Also based on https://github.com/compnerd/swift-build/blob/master/.ci/vs2019.yml
      shell: bash
      run: |
        set -x
        cd swift-build
        export ANDROID_NDK_HOME=${ANDROID_HOME}/ndk-bundle
        export ANDROID_TARGET_ARCHITECTURE=x86_64
        export ANDROID_TARGET_ABI="29"
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/lib/swift/dispatch/module.modulemap
        rm -rf ${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/lib/swift/CoreFoundation/module.modulemap
        rm -rf ${HOME}/.cache/clang
        cmake \
          -G Ninja \
          -S ${GITHUB_WORKSPACE}/swift-source/swift-corelibs-foundation \
          -B Foundation \
          -D CMAKE_Swift_COMPILER=${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr/bin/swiftc \
          -C ${GITHUB_WORKSPACE}/CMake/Android.cmake \
          -D CMAKE_Swift_SDK=${GITHUB_WORKSPACE}/Android/Swift/Android.sdk \
          -C ${GITHUB_WORKSPACE}/CMake/AndroidSwiftFlags.cmake \
          -D ANDROID_ALTERNATE_TOOLCHAIN=${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr \
          -D CMAKE_TOOLCHAIN_FILE=${ANDROID_HOME}/ndk-bundle/build/cmake/android.toolchain.cmake \
          -D CMAKE_BUILD_TYPE=Release \
          -D CMAKE_INSTALL_PREFIX=${GITHUB_WORKSPACE}/Android/Swift/Android.sdk/usr \
          -D ZLIB_LIBRARY=${GITHUB_WORKSPACE}/Android/zlib/usr/lib/libz.a \
          -D ZLIB_INCLUDE_DIR=${GITHUB_WORKSPACE}/Android/zlib/usr/include \
          -D CURL_LIBRARY=${GITHUB_WORKSPACE}/Android/cURL/usr/lib/libcurl.a \
          -D CURL_INCLUDE_DIR=${GITHUB_WORKSPACE}/Android/cURL/usr/include \
          -D ICU_INCLUDE_DIR=${GITHUB_WORKSPACE}/Android/ICU/include \
          -D ICU_UC_LIBRARY=${GITHUB_WORKSPACE}/Android/ICU/lib/libicuuc.so.67.1 \
          -D ICU_UC_LIBRARY_RELEASE=${GITHUB_WORKSPACE}/Android/ICU/lib/libicuuc.so.67.1 \
          -D ICU_I18N_LIBRARY=${GITHUB_WORKSPACE}/Android/ICU/lib/libicui18n.so.67.1 \
          -D ICU_I18N_LIBRARY_RELEASE=${GITHUB_WORKSPACE}/Android/ICU/lib/libicui18n.so.67.1 \
          -D LIBXML2_LIBRARY=${GITHUB_WORKSPACE}/Android/XML_2/usr/lib/libxml2.a \
          -D LIBXML2_INCLUDE_DIR=${GITHUB_WORKSPACE}/Android/XML_2/usr/include/libxml2 \
          -D dispatch_DIR=${GITHUB_WORKSPACE}/swift-build/Dispatch/cmake/modules \
          -D CMAKE_BUILD_WITH_INSTALL_RPATH=YES \
          -D CMAKE_HAVE_LIBC_PTHREAD=YES
        cmake --build Foundation --target install
