/*
 Resources.swift

 This source file is part of the Workspace open source project.
 https://github.com/SDGGiesbrecht/Workspace#workspace

 Copyright ©2018 Jeremy David Giesbrecht and the Workspace project contributors.

 Soli Deo gloria.

 Licensed under the Apache Licence, Version 2.0.
 See http://www.apache.org/licenses/LICENSE-2.0 for licence information.
 */

import Foundation

internal enum Resources {}

extension Resources {
    enum SwiftLint {
        static let standardConfiguration = String(data: Data(base64Encoded: "IyBTdGFuZGFyZCBDb25maWd1cmF0aW9uLnltbAojCiMgVGhpcyBzb3VyY2UgZmlsZSBpcyBwYXJ0IG9mIHRoZSBXb3Jrc3BhY2Ugb3BlbiBzb3VyY2UgcHJvamVjdC4KIyBodHRwczovL2dpdGh1Yi5jb20vU0RHR2llc2JyZWNodC9Xb3Jrc3BhY2Ujd29ya3NwYWNlCiMKIyBDb3B5cmlnaHQgwqkyMDE34oCTMjAxOCBKZXJlbXkgRGF2aWQgR2llc2JyZWNodCBhbmQgdGhlIFdvcmtzcGFjZSBwcm9qZWN0IGNvbnRyaWJ1dG9ycy4KIwojIFNvbGkgRGVvIGdsb3JpYS4KIwojIExpY2Vuc2VkIHVuZGVyIHRoZSBBcGFjaGUgTGljZW5jZSwgVmVyc2lvbiAyLjAuCiMgU2VlIGh0dHA6Ly93d3cuYXBhY2hlLm9yZy9saWNlbnNlcy9MSUNFTlNFLTIuMCBmb3IgbGljZW5jZSBpbmZvcm1hdGlvbi4KCmV4Y2x1ZGVkOgogICMg4oCi4oCi4oCi4oCi4oCi4oCi4oCiIFRvb2wgQ29tcGF0aWJpbGl0eSDigKLigKLigKLigKLigKLigKLigKIKICAjIFN3aWZ0IFBhY2thZ2UgTWFuYWdlcgogIC0gLmJ1aWxkCiAgLSBQYWNrYWdlcwogICMg4oCi4oCi4oCi4oCi4oCi4oCi4oCiIE90aGVyIOKAouKAouKAouKAouKAouKAouKAogogICMgTW9jayBwcm9qZWN0cyBuZWVkIHRvIGJlIGFibGUgdG8gZGVsaWJlcmF0ZWx5IGZhaWwuCiAgLSAiVGVzdHMvTW9jayBQcm9qZWN0cyIKCm9wdF9pbl9ydWxlczoKICAtIG9wZXJhdG9yX3VzYWdlX3doaXRlc3BhY2UKCmRpc2FibGVkX3J1bGVzOgogICMg4oCi4oCi4oCi4oCi4oCi4oCi4oCiIFdvcmtzcGFjZSBSdWxlcyDigKLigKLigKLigKLigKLigKLigKIKICAjIENvbG9uIFNwYWNpbmcKICAtIGNvbG9uCiAgIyDigKLigKLigKLigKLigKLigKLigKIgVGV4dCBTdHlsZSDigKLigKLigKLigKLigKLigKLigKIKICAjIFdyYXBwaW5nIGlzIGEgbWF0dGVyIG9mIGRpc3BsYXksIG5vdCBwYXJ0IG9mIHRoZSB0ZXh0LgogIC0gbGluZV9sZW5ndGgKICAjIOKAouKAouKAouKAouKAouKAouKAoiBTb3VyY2UgU3R5bGUg4oCi4oCi4oCi4oCi4oCi4oCi4oCiCiAgIyBOb3QgcmVhbGx5IHN0eWxlOyBpbnZvbHZlIHNlbWFudGljIGNoYW5nZXMKICAtIGZpbGVfbGVuZ3RoCiAgLSB0eXBlX2JvZHlfbGVuZ3RoCiAgLSBmdW5jdGlvbl9ib2R5X2xlbmd0aAogIC0gaWRlbnRpZmllcl9uYW1lCiAgLSB0eXBlX25hbWUKICAtIGxhcmdlX3R1cGxlCiAgLSBmdW5jdGlvbl9wYXJhbWV0ZXJfY291bnQKICAtIGN5Y2xvbWF0aWNfY29tcGxleGl0eQogIC0gbmVzdGluZwogIC0gZm9yY2VfY2FzdAo=")!, encoding: String.Encoding.utf8)!
    }

}
