
name: Build XML 2 for Android
runs:
  using: "composite"
  steps:
    - name: Build XML 2 for Android
      shell: bash
      run: |
        set -x
        cd libxml2
        export CC=$TOOLCHAIN/bin/x86_64-linux-android29-clang
        ./autogen.sh
        ./configure --host x86_64-linux-android \
          --prefix=${GITHUB_WORKSPACE}/Android/XML_2/usr
        make
        make install
