
name: Build XML 2 for Android
runs:
  using: "composite"
  steps:
    - name: Build XML 2 for Android
      # Based on https://github.com/GNOME/libxml2/tree/v2.9.10#readme
      shell: bash
      run: |
        set -x
        cd libxml2
        export NDK=${ANDROID_HOME}/ndk-bundle
        export HOST_TAG=linux-x86_64
        export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/$HOST_TAG
        export CC=$TOOLCHAIN/bin/x86_64-linux-android29-clang
        ./autogen.sh
        ./configure --host x86_64-linux-android \
          --prefix=${GITHUB_WORKSPACE}/Android/XML_2/usr
        make
        make install
