#if !canImport(ObjectiveC)
import XCTest

extension AllTasksTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AllTasksTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AllTasksTests.__allTests__AllTasksTests),
    ]
}
#endif
