/*
 Resources.swift

 This source file is part of the Workspace open source project.
 Diese Quelldatei ist Teil des qeulloffenen Workspace‐Projekt.
 https://github.com/SDGGiesbrecht/Workspace#workspace

 Copyright ©2018–2019 Jeremy David Giesbrecht and the Workspace project contributors.
 Urheberrecht ©2018–2019 Jeremy David Giesbrecht und die Mitwirkenden des Workspace‐Projekts.

 Soli Deo gloria.

 Licensed under the Apache Licence, Version 2.0.
 See http://www.apache.org/licenses/LICENSE-2.0 for licence information.
 */

import Foundation

internal enum Resources {}
internal typealias Ressourcen = Resources

extension Resources {
    static let proofreadScheme = String(data: Data(base64Encoded: "PCEtLQogUHJvb2ZyZWFkIFNjaGVtZS54Y3NjaGVtZQoKIFRoaXMgc291cmNlIGZpbGUgaXMgcGFydCBvZiB0aGUgV29ya3NwYWNlIG9wZW4gc291cmNlIHByb2plY3QuCiBEaWVzZSBRdWVsbGRhdGVpIGlzdCBUZWlsIGRlcyBxZXVsbG9mZmVuZW4gV29ya3NwYWNl4oCQUHJvamVrdC4KIGh0dHBzOi8vZ2l0aHViLmNvbS9TREdHaWVzYnJlY2h0L1dvcmtzcGFjZSN3b3Jrc3BhY2UKCiBDb3B5cmlnaHQgwqkyMDE44oCTMjAxOSBKZXJlbXkgRGF2aWQgR2llc2JyZWNodCBhbmQgdGhlIFdvcmtzcGFjZSBwcm9qZWN0IGNvbnRyaWJ1dG9ycy4KIFVyaGViZXJyZWNodCDCqTIwMTjigJMyMDE5IEplcmVteSBEYXZpZCBHaWVzYnJlY2h0IHVuZCBkaWUgTWl0d2lya2VuZGVuIGRlcyBXb3Jrc3BhY2XigJBQcm9qZWt0cy4KCiBTb2xpIERlbyBnbG9yaWEuCgogTGljZW5zZWQgdW5kZXIgdGhlIEFwYWNoZSBMaWNlbmNlLCBWZXJzaW9uIDIuMC4KIFNlZSBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjAgZm9yIGxpY2VuY2UgaW5mb3JtYXRpb24uCiAtLT4KCjw/eG1sIHZlcnNpb249IjEuMCIgZW5jb2Rpbmc9IlVURi04Ij8+CjxTY2hlbWUKICAgTGFzdFVwZ3JhZGVWZXJzaW9uID0gIjEwMDAiCiAgIHZlcnNpb24gPSAiMS4zIj4KICAgPEJ1aWxkQWN0aW9uPgogICAgICA8QnVpbGRBY3Rpb25FbnRyaWVzPgogICAgICAgICA8QnVpbGRBY3Rpb25FbnRyeT4KICAgICAgICAgICAgPEJ1aWxkYWJsZVJlZmVyZW5jZQogICAgICAgICAgICAgICBCdWlsZGFibGVJZGVudGlmaWVyID0gInByaW1hcnkiCiAgICAgICAgICAgICAgIEJsdWVwcmludElkZW50aWZpZXIgPSAiV09SS1NQQUNFX1BST09GUkVBRF9UQVJHRVQiCiAgICAgICAgICAgICAgIEJ1aWxkYWJsZU5hbWUgPSAiUHJvb2ZyZWFkIgogICAgICAgICAgICAgICBCbHVlcHJpbnROYW1lID0gIlByb29mcmVhZCIKICAgICAgICAgICAgICAgUmVmZXJlbmNlZENvbnRhaW5lciA9ICJjb250YWluZXI6Wypwcm9qZWN0Kl0iPgogICAgICAgICAgICA8L0J1aWxkYWJsZVJlZmVyZW5jZT4KICAgICAgICAgPC9CdWlsZEFjdGlvbkVudHJ5PgogICAgICA8L0J1aWxkQWN0aW9uRW50cmllcz4KICAgPC9CdWlsZEFjdGlvbj4KPC9TY2hlbWU+Cg==")!, encoding: String.Encoding.utf8)!

}
