# Based on https://github.com/compnerd/swift-build/blob/master/cmake/caches/curl.cmake

cmake_policy(SET CMP0077 NEW)

set(CMAKE_POSITION_INDEPENDENT_CODE ON CACHE BOOL "")

set(BUILD_CURL_EXE NO CACHE BOOL "")

set(CMAKE_USE_OPENSSL NO CACHE BOOL "")
set(CURL_CA_PATH "none" CACHE STRING "")

set(CMAKE_USE_LIBSSH2 NO CACHE BOOL "")

set(HAVE_POLL_FINE NO CACHE BOOL "")

set(CURL_DISABLE_LDAP YES CACHE BOOL "")
set(CURL_DISABLE_LDAPS YES CACHE BOOL "")

set(CURL_DISABLE_TELNET YES CACHE BOOL "")

set(CURL_DISABLE_DICT YES CACHE BOOL "")

set(CURL_DISABLE_FILE YES CACHE BOOL "")

set(CURL_DISABLE_TFTP YES CACHE BOOL "")

set(CURL_DISABLE_RTSP YES CACHE BOOL "")

set(CURL_DISABLE_PROXY YES CACHE BOOL "")

set(CURL_DISABLE_POP3 YES CACHE BOOL "")
set(CURL_DISABLE_IMAP YES CACHE BOOL "")
set(CURL_DISABLE_SMTP YES CACHE BOOL "")

set(CURL_DISABLE_GOPHER YES CACHE BOOL "")

set(CURL_ZLIB YES CACHE BOOL "")

set(ENABLE_UNIX_SOCKETS NO CACHE BOOL "")

set(ENABLE_THREADED_RESOLVER NO CACHE BOOL "")
