# Standard Configuration.yml
#
# This source file is part of the Workspace open source project.
# https://github.com/SDGGiesbrecht/Workspace#workspace
#
# Copyright ©2017–2018 Jeremy David Giesbrecht and the Workspace project contributors.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

excluded:
  # ••••••• Tool Compatibility •••••••
  # Swift Package Manager
  - .build
  - Packages
  # ••••••• Other •••••••
  # Mock projects need to be able to deliberately fail.
  - "Tests/Mock Projects"

opt_in_rules:
  - operator_usage_whitespace

disabled_rules:
  # ••••••• Workspace Rules •••••••
  # Colon Spacing
  - colon
  # ••••••• Text Style •••••••
  # Wrapping is a matter of display, not part of the text.
  - line_length
  # ••••••• Source Style •••••••
  # Not really style; involve semantic changes
  - file_length
  - type_body_length
  - function_body_length
  - identifier_name
  - type_name
  - large_tuple
  - function_parameter_count
  - cyclomatic_complexity
  - nesting
  - force_cast
