

name: Build Toolchains

on: [push, pull_request]

jobs:
  ICU_Android:
    name: ICU (Android)
    runs-on: ubuntu-18.04
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Make space
      uses: ./.github/Workflow Steps/Make Space
    - name: Install Swift dependencies
      uses: ./.github/Workflow Steps/Install Swift Dependencies
    - name: Fetch Android NDK
      uses: ./.github/Workflow Steps/Fetch Android NDK
    - name: Create Android C toolchain
      uses: ./.github/Workflow Steps/Create Android C Toolchain
    - name: Fetch ICU source
      uses: ./.github/Workflow Steps/Fetch ICU Source
    - name: Build ICU for Ubuntu
      uses: ./.github/Workflow Steps/Build ICU for Ubuntu
    - name: Build ICU for Android
      uses: ./.github/Workflow Steps/Build ICU for Android
    - name: Upload ICU
      uses: actions/upload-artifact@v1
      with:
        name: ICU
        path: Android/ICU
  zlib_Android:
    name: zlib (Android)
    runs-on: ubuntu-18.04
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Make space
      uses: ./.github/Workflow Steps/Make Space
    - name: Install Swift dependencies
      uses: ./.github/Workflow Steps/Install Swift Dependencies
    - name: Fetch Android NDK
      uses: ./.github/Workflow Steps/Fetch Android NDK
    - name: Fetch zlib source
      uses: ./.github/Workflow Steps/Fetch zlib Source
    - name: Build zlib for Android
      uses: ./.github/Workflow Steps/Build zlib for Android
    - name: Upload zlib
      uses: actions/upload-artifact@v1
      with:
        name: zlib
        path: Android/zlib
  cURL_Android:
    name: cURL (Android)
    runs-on: ubuntu-18.04
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Make space
      uses: ./.github/Workflow Steps/Make Space
    - name: Install Swift dependencies
      uses: ./.github/Workflow Steps/Install Swift Dependencies
    - name: Fetch Android NDK
      uses: ./.github/Workflow Steps/Fetch Android NDK
    - name: Fetch cURL source
      uses: ./.github/Workflow Steps/Fetch cURL Source
    - name: Build cURL for Android
      uses: ./.github/Workflow Steps/Build cURL for Android
    - name: Upload cURL
      uses: actions/upload-artifact@v1
      with:
        name: cURL
        path: Android/cURL
  XML_2_Android:
    name: XML 2 (Android)
    runs-on: ubuntu-18.04
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Make space
      uses: ./.github/Workflow Steps/Make Space
    - name: Install Swift dependencies
      uses: ./.github/Workflow Steps/Install Swift Dependencies
    - name: Fetch Android NDK
      uses: ./.github/Workflow Steps/Fetch Android NDK
    - name: Fetch XML 2 source
      uses: ./.github/Workflow Steps/Fetch XML 2 Source
    - name: Build XML 2 for Android
      uses: ./.github/Workflow Steps/Build XML 2 for Android
    - name: Upload XML 2
      uses: actions/upload-artifact@v1
      with:
        name: XML 2
        path: Android/XML_2
  Swift_Ubuntu:
    name: Swift (Ubuntu)
    runs-on: ubuntu-18.04
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Make space
      uses: ./.github/Workflow Steps/Make Space
    - name: Install Swift dependencies
      uses: ./.github/Workflow Steps/Install Swift Dependencies
    - name: Fetch Swift source
      uses: ./.github/Workflow Steps/Fetch Swift Source
    - name: Build Swift for Ubuntu
      uses: ./.github/Workflow Steps/Build Swift for Ubuntu
    - name: Upload Swift for Ubuntu
      uses: actions/upload-artifact@v1
      with:
        name: Swift
        path: Ubuntu/Swift
  Swift_Android:
    name: Swift (Android)
    runs-on: ubuntu-18.04
    needs: [ICU_Android, zlib_Android, cURL_Android, XML_2_Android]
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Make space
      uses: ./.github/Workflow Steps/Make Space
    - name: Install Swift dependencies
      uses: ./.github/Workflow Steps/Install Swift Dependencies
    - name: Fetch Android NDK
      uses: ./.github/Workflow Steps/Fetch Android NDK
    - name: Install Android NDK
      uses: ./.github/Workflow Steps/Install Android NDK
    - name: Fetch Swift source
      uses: ./.github/Workflow Steps/Fetch Swift Source
    - name: Download ICU
      uses: actions/download-artifact@v1
      with:
        name: ICU
        path: Android/ICU
    - name: Download zlib
      uses: actions/download-artifact@v1
      with:
        name: zlib
        path: Android/zlib
    - name: Download cURL
      uses: actions/download-artifact@v1
      with:
        name: cURL
        path: Android/cURL
    - name: Download XML 2
      uses: actions/download-artifact@v1
      with:
        name: XML 2
        path: Android/XML_2
    - name: Build Swift SDK for Android
      uses: ./.github/Workflow Steps/Build Swift SDK for Android
    - name: Embed ICU
      uses: ./.github/Workflow Steps/Embed ICU
      # The standard build script currently fails to include core libraries.
    - name: Build Dispatch for Android
      uses: ./.github/Workflow Steps/Build Dispatch for Android
    - name: Build Foundation for Android
      uses: ./.github/Workflow Steps/Build Foundation for Android
    - name: Build XCTest for Android
      uses: ./.github/Workflow Steps/Build XCTest for Android
    - name: Install Dispatch for Android
      uses: ./.github/Workflow Steps/Install Dispatch for Android
    - name: Thin Swift SDK for Android
      uses: ./.github/Workflow Steps/Thin Swift SDK for Android
    - name: Upload Swift SDK for Android
      uses: actions/upload-artifact@v1
      with:
        name: Android.sdk
        path: Android/Swift
  Hello_World_Android:
    name: 'Hello, World! (Android)'
    runs-on: ubuntu-18.04
    needs: [Swift_Ubuntu, Swift_Android]
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Make space
      uses: ./.github/Workflow Steps/Make Space
    - name: Install Swift dependencies
      uses: ./.github/Workflow Steps/Install Swift Dependencies
    - name: Fetch Android NDK
      uses: ./.github/Workflow Steps/Fetch Android NDK
    - name: Download Swift for Ubuntu
      uses: actions/download-artifact@v1
      with:
        name: Swift
        path: Ubuntu/Swift
    - name: Repair toolchain permissions
      uses: ./.github/Workflow Steps/Repair Toolchain Permissions
    - name: Download Android SDK
      uses: actions/download-artifact@v1
      with:
        name: Android.sdk
        path: Android/Swift
    - name: Build test package
      uses: ./.github/Workflow Steps/Build Test Package
    - name: Copy libraries
      uses: ./.github/Workflow Steps/Copy Libraries
    - name: Upload package products
      uses: actions/upload-artifact@v1
      with:
        name: Hello_World
        path: HelloWorld/.build/x86_64-unknown-linux-android/debug
  Android_Emulator:
    name: Android Emulator
    runs-on: macos-10.15
    needs: [Hello_World_Android]
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Download tests
      uses: actions/download-artifact@v1
      with:
        name: Hello_World
        path: .build/x86_64-unknown-linux-android/debug
    - name: Prepare emulator
      uses: ./.github/Workflow Steps/Prepare Emulator
    - name: Test
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        arch: x86_64
        script: .build/SDG/Emulator.sh
