
name: Build Toolchains

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-18.04
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Install Swift dependencies
      shell: bash
      run: |
        set -x
        sudo apt-get update --assume-yes
        sudo apt-get install --assume-yes \
          clang \
          cmake \
          git \
          icu-devtools \
          libcurl4-openssl-dev \
          libedit-dev \
          libicu-dev \
          libncurses5-dev \
          libpython-dev \
          libsqlite3-dev \
          libxml2-dev \
          ninja-build \
          pkg-config \
          python \
          python-six \
          rsync \
          swig \
          systemtap-sdt-dev \
          tzdata \
          uuid-dev
    - name: Check Android NDK
      shell: bash
      run: |
        set -x
        export PATH="${ANDROID_HOME}/ndk-bundle:${PATH}"
        echo "::set-env name=PATH::${PATH}"
        which ndk-build
    - name: Fetch ICU source
      shell: bash
      run: |
        set -x
        git clone https://github.com/unicode-org/icu --branch release-65-1 --depth 1
    - name: Build ICU for Linux
      shell: bash
      run: |
        set -x
        mkdir icu4c-build-linux
        cd icu4c-build-linux
        ../icu/icu4c/source/runConfigureICU Linux
        make
    - name: Build ICU for Android
      shell: bash
      run: |
        set -x
        mkdir icu4c-build-android
        cd icu4c-build-android
        ../icu/icu4c/source/configure \
          --host=x86_64-unknown-linux-android \
          --with-cross-build=${GITHUB_WORKSPACE}/icu4c-build-linux \
          --prefix=${GITHUB_WORKSPACE}/Android/ICU
        make
        make install
        find ${GITHUB_WORKSPACE}/Android/ICU
    - name: Fetch Swift source
      shell: bash
      run: |
        set -x
        mkdir swift-source
        cd swift-source
        git clone https://github.com/apple/swift.git
        ./swift/utils/update-checkout --clone
    - name: Build Swift toolchain
      shell: bash
      run: |
        set -x
        cd swift-source/swift
        utils/build-script --release \
          --android \
          --android-ndk ${ANDROID_HOME}/ndk-bundle \
          --android-arch x86_64 \
          --android-api-level 29 \
          --android-icu-uc ${GITHUB_WORKSPACE}/Android/ICU/lib/libicuuc.so \
          --android-icu-uc-include ${GITHUB_WORKSPACE}/icu/icu4c/source/common \
          --android-icu-i18n ${GITHUB_WORKSPACE}/Android/ICU/lib/libicui18n.so \
          --android-icu-i18n-include ${GITHUB_WORKSPACE}/icu/icu4c/source/i18n \
          --android-icu-data ${GITHUB_WORKSPACE}/Android/ICU/lib/libicudata.so
