# Swift 5.6 (Ubuntu).yaml
#
# This source file is part of the Workspace open source project.
# Diese Quelldatei ist Teil des quelloffenen Arbeitsbereich‐Projekt.
# https://github.com/SDGGiesbrecht/Workspace#workspace
#
# Copyright ©2022 Jeremy David Giesbrecht and the Workspace project contributors.
# Urheberrecht ©2022 Jeremy David Giesbrecht und die Mitwirkenden des Arbeitsbereich‐Projekts.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: Swift 5.6 (Ubuntu)

on: [push, pull_request]

jobs:
  Ubuntu:
    name: Swift 5.6 (Ubuntu)
    runs-on: ubuntu-20.04
    container: swift:5.6.0-focal
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install SwiftPM dependencies
      shell: bash
      run: |
        set -x
        apt-get update --assume-yes
        UCF_FORCE_CONFOLD=1 DEBIAN_FRONTEND=noninteractive \
        apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
          install --assume-yes \
            libncurses-dev \
            libsqlite3-dev
    - name: Install Workspace dependencies
      shell: bash
      run: |
        set -x
        apt-get update --assume-yes
        UCF_FORCE_CONFOLD=1 DEBIAN_FRONTEND=noninteractive \
        apt-get -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" \
          install --assume-yes \
            curl
    - name: Validate
      shell: bash
      run: |
        set -x
        swift test
