# Swift 5.6 (Windows).yaml
#
# This source file is part of the Workspace open source project.
# Diese Quelldatei ist Teil des quelloffenen Arbeitsbereich‐Projekt.
# https://github.com/SDGGiesbrecht/Workspace#workspace
#
# Copyright ©2022 Jeremy David Giesbrecht and the Workspace project contributors.
# Urheberrecht ©2022 Jeremy David Giesbrecht und die Mitwirkenden des Arbeitsbereich‐Projekts.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: Swift 5.6 (Windows)

on: [push, pull_request]

jobs:
  Windows:
    name: Swift 5.6 (Windows)
    runs-on: windows-2019
    steps:
    - name: Check out
      uses: actions/checkout@v2
    - name: Install Swift
      uses: compnerd/gha-setup-swift@cf2a61060c146203ea6fe10cce367979ae4ec0b1
      with:
        branch: swift-5.6-release
        tag: 5.6-RELEASE
    - name: Test
      shell: cmd
      run: |
        echo on
        set TARGETING_WINDOWS=true
        swift test
