name: Toolchain Assembly

on: [push, pull_request]

jobs:
  Linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Fetch Swift repository
      run: git clone https://github.com/apple/swift
