# Web.yaml
#
# This source file is part of the Workspace open source project.
# Diese Quelldatei ist Teil des quelloffenen Arbeitsbereich‐Projekt.
# https://github.com/SDGGiesbrecht/Workspace#workspace
#
# Copyright ©2021 Jeremy David Giesbrecht and the Workspace project contributors.
# Urheberrecht ©2021 Jeremy David Giesbrecht und die Mitwirkenden des Arbeitsbereich‐Projekts.
#
# Soli Deo gloria.
#
# Licensed under the Apache Licence, Version 2.0.
# See http://www.apache.org/licenses/LICENSE-2.0 for licence information.

name: Web

on: [push, pull_request]

jobs:
  Web:
    name: Web
    runs-on: macos-11
    steps:
    - name: Check out
      uses: actions/checkout@v1
    - name: Cache Workspace
      uses: actions/cache@v1
      with:
        key: Web‐${{ hashFiles('.github/workflows/**') }}
        path: .build/SDG/Workspace
    - name: Install Carton
      shell: bash
      run: |
        set -x
        cd ..
        git clone https://github.com/swiftwasm/homebrew-tap
        cd homebrew-tap
        git checkout 74e1deea6545fd0666c0539e835c918ae00b52a8
        brew install carton.rb
        brew switch carton 0.12.1
    - name: Test
      shell: bash
      run: |
        set -x
        export TARGETING_WEB=true
        carton test
